---
sudo: false
language: ruby
services:
  - docker
cache: bundler
before_install:
  - gem update bundler
script: "bundle exec pdqtest setup && bundle exec pdqtest all"
rvm:
  - 2.2.2
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 4.7.0"
